import blue from "@material-ui/core/colors/blue";
import green from "@material-ui/core/colors/green";
import red from "@material-ui/core/colors/red";
import purple from "@material-ui/core/colors/purple";

/**
 * Template plaject呼び出しで利用するコンテンツ情報を保持する
 */
export interface TemplateContents {
  icon: string;
  title: string;
  description: string;
  code: any;
  iconColor: string;
}

const ICONS = {
  mailSend: "send",
  mailEdit: "rate_review",
  timeDisable: "timer_off",
  spreadsheet: "border_all",
  calendar: "event",
};

const COLORS = {
  blue: blue[800],
  green: green[800],
  red: red[800],
  purple: purple[800],
};

export const templateProjectDatas: TemplateContents[] = [
  {
    icon: ICONS.mailSend,
    iconColor: COLORS.blue,
    title: "今日の予定一覧を送信",
    description: "カレンダーに登録されている今日の予定件名一覧をGmailで送ります",
    code: {
      current: [
        { currentGroupId: "root", currentParentCardId: "root", currentParentGroupId: "root", argsFromParent: [] },
      ],
      entities: {
        root: [
          {
            id: "179da4e67c919b7edd88b2995b608ee",
            categoryId: "Calendar",
            methodId: "openDefault",
            inputBaseValue: "",
            inputArgumentValue: [],
            outputVariableName: "calender",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "179da4f71992978f0b5a11a2c779218",
            categoryId: "Date",
            methodId: "TodayDate",
            inputBaseValue: "",
            inputArgumentValue: [],
            outputVariableName: "today",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "179da4fae3c257879f11518bb669ead",
            categoryId: "Calendar",
            methodId: "getEventsForDay",
            inputBaseValue: "$calender$",
            inputArgumentValue: [{ key: "date", value: "$today$", isObject: false }],
            outputVariableName: "events",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "179da5050a92255a92e102488e0765c",
            categoryId: "Array",
            methodId: "map",
            inputBaseValue: "$events$",
            inputArgumentValue: [],
            outputVariableName: "result",
            comment: "",
            childGroupId: "group1",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "179da5170e41f46286c15186421fd01",
            categoryId: "Array",
            methodId: "join",
            inputBaseValue: "$result$",
            inputArgumentValue: [{ key: "value", value: "'\\n'", isObject: false }],
            outputVariableName: "body",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "179da521197284cea92be2461185caa",
            categoryId: "Gmail",
            methodId: "sendEmail",
            inputBaseValue: "",
            inputArgumentValue: [
              { key: "recipient", value: "'xxxxxxxxxx@gmail.com'", isObject: false },
              { key: "subject", value: "'本日の予定をお送りします'", isObject: false },
              { key: "body", value: "$body$", isObject: false },
              { key: "attachments", value: "", isObject: true },
              { key: "bcc", value: "", isObject: true },
              { key: "cc", value: "", isObject: true },
              { key: "from", value: "", isObject: true },
              { key: "htmlBody", value: "", isObject: true },
              { key: "name", value: "", isObject: true },
            ],
            outputVariableName: "",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
        ],
        group1: [
          {
            id: "179da50af772671131d1329e59cdca1",
            categoryId: "CalendarEvent",
            methodId: "getTitle",
            inputBaseValue: "$group1Value$",
            inputArgumentValue: [],
            outputVariableName: "title",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "179da5050a92255a92e102488e0765c" },
            groupId: "group1",
          },
          {
            id: "179da5109661ac9a74bea2e2f96c306",
            categoryId: "Array",
            methodId: "return",
            inputBaseValue: "$title$",
            inputArgumentValue: [],
            outputVariableName: "",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "179da5050a92255a92e102488e0765c" },
            groupId: "group1",
          },
        ],
      },
      RunOptions: { categoryId: "", methodId: "", frequency1Argument: "", frequency2Argument: "" },
    },
  },
  {
    icon: ICONS.mailEdit,
    iconColor: COLORS.green,
    title: "GmailをSpreadsheet書き込み",
    description: "Gmailの受信トレイにある件名の一覧をSpreadsheetに書き出します",
    code: {
      current: [
        { currentGroupId: "root", currentParentCardId: "root", currentParentGroupId: "root", argsFromParent: [] },
      ],
      entities: {
        root: [
          {
            id: "179da558d39183feb9188281b0b120c",
            categoryId: "Gmail",
            methodId: "search",
            inputBaseValue: "",
            inputArgumentValue: [
              { key: "query", value: "'label:inbox'", isObject: false },
              { key: "start", value: "0", isObject: false },
              { key: "max", value: "30", isObject: false },
            ],
            outputVariableName: "threads",
            comment: "受信トレイよりGmailスレッドを取得します",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "179da6166dc2ad752db8d24f7b37ba6",
            categoryId: "Spreadsheet",
            methodId: "getActiveSpreadsheet",
            inputBaseValue: "",
            inputArgumentValue: [],
            outputVariableName: "spreadsheet",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "179da61b04e2365b211c525cba4e69b",
            categoryId: "Spreadsheet",
            methodId: "getSheetByName",
            inputBaseValue: "$spreadsheet$",
            inputArgumentValue: [{ key: "name", value: "'sheetName'", isObject: false }],
            outputVariableName: "sheet",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "179da5687fe1a7c342dd72b26c73b8e",
            categoryId: "Array",
            methodId: "forEach",
            inputBaseValue: "$threads$",
            inputArgumentValue: [],
            outputVariableName: "result",
            comment: "",
            childGroupId: "group1",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
        ],
        group1: [
          {
            id: "179da57d07324b4a89f562bb5d1333c",
            categoryId: "GmailThread",
            methodId: "getFirstMessageSubject",
            inputBaseValue: "$group1Value$",
            inputArgumentValue: [],
            outputVariableName: "subject",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "179da5687fe1a7c342dd72b26c73b8e" },
            groupId: "group1",
          },
          {
            id: "179da588c701b9456b53f2e6d6088d2",
            categoryId: "GmailThread",
            methodId: "getMessages",
            inputBaseValue: "$group1Value$",
            inputArgumentValue: [],
            outputVariableName: "messages",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "179da5687fe1a7c342dd72b26c73b8e" },
            groupId: "group1",
          },
          {
            id: "179da594a1f2d2d13efd92d7a24ab0c",
            categoryId: "Array",
            methodId: "indexAccess",
            inputBaseValue: "$messages$",
            inputArgumentValue: [{ key: "value", value: "0", isObject: false }],
            outputVariableName: "message",
            comment: "スレッドの最初のメッセージにアクセスする",
            childGroupId: "group2",
            parentGroup: { grouptId: "root", id: "179da5687fe1a7c342dd72b26c73b8e" },
            groupId: "group1",
          },
          {
            id: "179da59e28e26356ac1452165b73d31",
            categoryId: "GmailMessage",
            methodId: "getFrom",
            inputBaseValue: "$message$",
            inputArgumentValue: [],
            outputVariableName: "fromAddress",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "179da5687fe1a7c342dd72b26c73b8e" },
            groupId: "group1",
          },
          {
            id: "179da5a67221c8187c5f02afaba766c",
            categoryId: "Literal",
            methodId: "BlankArrayLiteral",
            inputBaseValue: "",
            inputArgumentValue: [],
            outputVariableName: "array",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "179da5687fe1a7c342dd72b26c73b8e" },
            groupId: "group1",
          },
          {
            id: "179da5b782429770a53162703fbb360",
            categoryId: "Array",
            methodId: "push",
            inputBaseValue: "$array$",
            inputArgumentValue: [{ key: "value", value: "$subject$", isObject: false }],
            outputVariableName: "",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "179da5687fe1a7c342dd72b26c73b8e" },
            groupId: "group1",
          },
          {
            id: "179da5bd0fa21bd4d2ad720173e3934",
            categoryId: "Array",
            methodId: "push",
            inputBaseValue: "$array$",
            inputArgumentValue: [{ key: "value", value: "$fromAddress$", isObject: false }],
            outputVariableName: "",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "179da5687fe1a7c342dd72b26c73b8e" },
            groupId: "group1",
          },
          {
            id: "179da84e1f42a07ab44b4212d435320",
            categoryId: "SpreadsheetSheet",
            methodId: "appendRow",
            inputBaseValue: "$sheet$",
            inputArgumentValue: [{ key: "array", value: "$array$", isObject: false }],
            outputVariableName: "",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "179da5687fe1a7c342dd72b26c73b8e" },
            groupId: "group1",
          },
        ],
        group2: [],
      },
      RunOptions: { categoryId: "", methodId: "", frequency1Argument: "", frequency2Argument: "" },
    },
  },
  {
    icon: ICONS.mailSend,
    iconColor: COLORS.blue,
    title: "Gmailを毎日送信",
    description: "毎日指定時間にGmailを送信します",
    code: {
      current: [
        { currentGroupId: "root", currentParentCardId: "root", currentParentGroupId: "root", argsFromParent: [] },
      ],
      RunOptions: { categoryId: "TimeTrigger", methodId: "everyDays", frequency1Argument: "9", frequency2Argument: "" },
      entities: {
        root: [
          {
            id: "17a9b0aca3d27a5abbff51f3a97258a",
            categoryId: "Literal",
            methodId: "StringLiteral",
            inputBaseValue: "'xxxxxxxxxx@gmail.com'",
            inputArgumentValue: [],
            outputVariableName: "recipient",
            comment: "送信先メールアドレス",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "17a9b0b51442c06fbc28b1f5d07fffc",
            categoryId: "Gmail",
            methodId: "sendEmail",
            inputBaseValue: "",
            inputArgumentValue: [
              { key: "recipient", value: "$recipient$", isObject: false },
              { key: "subject", value: "'【自動送信】件名'", isObject: false },
              {
                key: "body",
                value: "'宛先各位\\n\\nGASにてメールを送信してみます。\\nご確認下さい。\\n'",
                isObject: false,
              },
              { key: "attachments", value: "", isObject: true },
              { key: "bcc", value: "", isObject: true },
              { key: "cc", value: "", isObject: true },
              { key: "from", value: "", isObject: true },
              { key: "htmlBody", value: "", isObject: true },
              { key: "name", value: "", isObject: true },
            ],
            outputVariableName: "",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
        ],
      },
    },
  },
  {
    icon: ICONS.timeDisable,
    iconColor: COLORS.red,
    title: "全てのトリガーを削除",
    description: "スクリプトに設定された全てのトリガーを削除します",
    code: {
      current: [
        { currentGroupId: "root", currentParentCardId: "root", currentParentGroupId: "root", argsFromParent: [] },
      ],
      RunOptions: { categoryId: "", methodId: "", frequency1Argument: "", frequency2Argument: "" },
      entities: {
        root: [
          {
            id: "17a9b20f1dc19b478c822213769faaf",
            categoryId: "Utility",
            methodId: "deleteAllTrigger",
            inputBaseValue: "",
            inputArgumentValue: [],
            outputVariableName: "",
            comment: "全てのトリガーを削除",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
        ],
      },
    },
  },
  {
    icon: ICONS.spreadsheet,
    iconColor: COLORS.green,
    title: "Spreadsheetの値をGmailで送付",
    description: "Spreadsheetの指定セルの値をGmailで送信します",
    code: {
      current: [
        { currentGroupId: "root", currentParentCardId: "root", currentParentGroupId: "root", argsFromParent: [] },
      ],
      RunOptions: { categoryId: "", methodId: "", frequency1Argument: "", frequency2Argument: "" },
      entities: {
        root: [
          {
            id: "17a9b2534412adce382832cd8a8bda9",
            categoryId: "Spreadsheet",
            methodId: "getActiveSpreadsheet",
            inputBaseValue: "",
            inputArgumentValue: [],
            outputVariableName: "ss",
            comment: "スクリプトが紐づくSpreadsheetへアクセス",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "17a9b259f4b25cc01ab4828d9390518",
            categoryId: "Spreadsheet",
            methodId: "getSheetByName",
            inputBaseValue: "$ss$",
            inputArgumentValue: [{ key: "name", value: "'シート名'", isObject: false }],
            outputVariableName: "sheet",
            comment: "引数-0のシートを開く",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "17a9b270c342bcdbe4c6c2c774ad930",
            categoryId: "SpreadsheetSheet",
            methodId: "getRangeByString",
            inputBaseValue: "$sheet$",
            inputArgumentValue: [{ key: "range", value: "'A1'", isObject: false }],
            outputVariableName: "range",
            comment: "A1セルを範囲選択します",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "17a9b27e52f18fb5dcf7d24d75a05f5",
            categoryId: "SpreadsheetRange",
            methodId: "getValue",
            inputBaseValue: "$range$",
            inputArgumentValue: [],
            outputVariableName: "value",
            comment: "指定したセルの値を取得します",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "17a9b28701125d263f2d12d15c5ca65",
            categoryId: "Gmail",
            methodId: "sendEmail",
            inputBaseValue: "",
            inputArgumentValue: [
              { key: "recipient", value: "'xxxxxxxx@gmail.com'", isObject: false },
              { key: "subject", value: "'【自動送信】Spreadsheetの取得結果を送付します'", isObject: false },
              { key: "body", value: "'宛先各位\\n\\n対象のSpreadsheetA1の値は'+$value$+'\\n\\nです'", isObject: false },
              { key: "attachments", value: "", isObject: true },
              { key: "bcc", value: "", isObject: true },
              { key: "cc", value: "", isObject: true },
              { key: "from", value: "", isObject: true },
              { key: "htmlBody", value: "", isObject: true },
              { key: "name", value: "", isObject: true },
            ],
            outputVariableName: "",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
        ],
      },
    },
  },
  {
    icon: ICONS.calendar,
    iconColor: COLORS.purple,
    title: "予定を毎週自動作成",
    description: "毎週月曜日早朝に同日9時開始の予定を自動作成します",
    code: {
      current: [
        { currentGroupId: "root", currentParentCardId: "root", currentParentGroupId: "root", argsFromParent: [] },
      ],
      RunOptions: { categoryId: "", methodId: "", frequency1Argument: "", frequency2Argument: "" },
      entities: {
        root: [
          {
            id: "17a9b2d4bbb259a15a0c61bee4a36f4",
            categoryId: "Calendar",
            methodId: "openDefault",
            inputBaseValue: "",
            inputArgumentValue: [],
            outputVariableName: "calender",
            comment: "実行者のカレンダーへアクセス",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "17a9b2de7de2bc9f9f7231f8d58be05",
            categoryId: "Date",
            methodId: "TodayDate",
            inputBaseValue: "",
            inputArgumentValue: [],
            outputVariableName: "today",
            comment: "実行日時を取得",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "17a9b2e7ad923c0b67e142cc620fc02",
            categoryId: "Date",
            methodId: "setHour",
            inputBaseValue: "$today$",
            inputArgumentValue: [{ key: "num", value: "9", isObject: false }],
            outputVariableName: "",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "17a9b2ed144221fd0e7861f39169ea8",
            categoryId: "Date",
            methodId: "setMinutes",
            inputBaseValue: "$today$",
            inputArgumentValue: [{ key: "num", value: "0", isObject: false }],
            outputVariableName: "",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
          {
            id: "17a9b2f406025d5ca3a1d2cb7f69f54",
            categoryId: "Calendar",
            methodId: "createEvent",
            inputBaseValue: "$calender$",
            inputArgumentValue: [
              { key: "title", value: "'【定期】自動生成イベント'", isObject: false },
              { key: "start", value: "$today$", isObject: false },
              { key: "end", value: "$today$", isObject: false },
              { key: "description", value: "'予定を作成しました'", isObject: true },
              { key: "location", value: "'Web会議'", isObject: true },
              { key: "guests", value: "", isObject: true },
              { key: "sendInvites", value: "true", isObject: true },
            ],
            outputVariableName: "event",
            comment: "",
            childGroupId: "",
            parentGroup: { grouptId: "root", id: "root" },
            groupId: "root",
          },
        ],
      },
    },
  },
];
